# Generated by Django 2.2.6 on 2019-11-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_courselist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselist',
            name='course_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
