# Generated by Django 2.2 on 2019-11-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='password',
        ),
        migrations.AddField(
            model_name='product',
            name='username',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
